import SwiftUI

public struct UPCascaderNode: Identifiable, Equatable, Sendable { public let id: String; public var value: String; public var label: String; public var children: [Self]; public init(id: String? = nil, value: String, label: String, children: [Self] = []) { self.id = id ?? value; self.value = value; self.label = label; self.children = children } }
@MainActor private final class UPCascadeSelection { var values: [String] = [] }
@MainActor public struct UPCascader: View {
    public var data: [UPCascaderNode]; public var show: Bool; public var valueKey: String; public var labelKey: String; public var childrenKey: String; public var maskCloseAble: Bool; public var zIndex: CGFloat; public var autoClose: Bool; public var headerDirection: String; public var optionsCols: Int; public var closeable: Bool
    private var modelValue: Binding<[String]>?; private let selection = UPCascadeSelection(); private var onChangeHandler: (([String]) -> Void)?; private var onConfirmHandler: (([String]) -> Void)?; private var onCancelHandler: (() -> Void)?
    public init(data: [UPCascaderNode] = [], modelValue: Binding<[String]>? = nil, show: Bool = false, valueKey: String = "value", labelKey: String = "label", childrenKey: String = "children", maskCloseAble: Bool = true, zIndex: some UPImageUnitValue = 0, autoClose: Bool = false, headerDirection: String = "row", optionsCols: Int = 2, closeable: Bool = true) { self.data = data; self.modelValue = modelValue; self.show = show; self.valueKey = valueKey; self.labelKey = labelKey; self.childrenKey = childrenKey; self.maskCloseAble = maskCloseAble; self.zIndex = UPUnit.parse(zIndex.upImageUnitValue); self.autoClose = autoClose; self.headerDirection = headerDirection; self.optionsCols = optionsCols; self.closeable = closeable; selection.values = modelValue?.wrappedValue ?? [] }
    public var body: some View { List(data) { Text($0.label) } }
    public func select(path: [Int]) { var nodes = data; var values: [String] = []; for index in path { guard nodes.indices.contains(index) else { break }; let node = nodes[index]; values.append(node.value); nodes = node.children }; selection.values = values; onChangeHandler?(values); if autoClose, nodes.isEmpty { confirm() } }
    public func confirm() { modelValue?.wrappedValue = selection.values; onConfirmHandler?(selection.values) }; public func cancel() { onCancelHandler?() }
    public func onChange(_ a: @escaping ([String]) -> Void) -> Self { var c = self; c.onChangeHandler = a; return c }; public func onConfirm(_ a: @escaping ([String]) -> Void) -> Self { var c = self; c.onConfirmHandler = a; return c }; public func onCancel(_ a: @escaping () -> Void) -> Self { var c = self; c.onCancelHandler = a; return c }
}

public struct UPSelectOption: Identifiable, Equatable, Sendable { public let id: String; public var name: String; public init(id: String, name: String) { self.id = id; self.name = name } }
@MainActor public struct UPSelect: View {
    public var options: [UPSelectOption]; public var current: String; public var maxHeight: String; public var overlay: Bool; public var overlayOpacity: Double; public var duration: Int; public var label: String; public var keyName: String; public var labelName: String; public var showOptionsLabel: Bool; public var zIndex: CGFloat; public var disabled: Bool; public var border: Bool; public var optionsWidth: String
    private var currentBinding: Binding<String>?; private var onSelectHandler: ((UPSelectOption) -> Void)?
    public init(options: [UPSelectOption] = [], current: Binding<String>? = nil, maxHeight: String = "90vh", overlay: Bool = true, overlayOpacity: Double = 0.01, duration: Int = 300, label: String = "选项", keyName: String = "id", labelName: String = "name", showOptionsLabel: Bool = false, zIndex: CGFloat = 11000, disabled: Bool = false, border: Bool = false, optionsWidth: String = "") { self.options = options; self.currentBinding = current; self.current = current?.wrappedValue ?? ""; self.maxHeight = maxHeight; self.overlay = overlay; self.overlayOpacity = overlayOpacity; self.duration = duration; self.label = label; self.keyName = keyName; self.labelName = labelName; self.showOptionsLabel = showOptionsLabel; self.zIndex = zIndex; self.disabled = disabled; self.border = border; self.optionsWidth = optionsWidth }
    public var body: some View { Menu(label) { ForEach(options) { option in Button(option.name) { select(option.id) } } }.disabled(disabled) }
    public func select(_ id: String) { guard !disabled, let option = options.first(where: { $0.id == id }) else { return }; currentBinding?.wrappedValue = id; onSelectHandler?(option) }; public func onSelect(_ a: @escaping (UPSelectOption) -> Void) -> Self { var c = self; c.onSelectHandler = a; return c }
}

public struct UPChooseOption: Identifiable, Equatable, Sendable { public var value: String; public var title: String; public var id: String { value }; public init(value: String, title: String) { self.value = value; self.title = title } }
@MainActor public struct UPChoose: View {
    public var options: [UPChooseOption]; public var type: String; public var itemWidth: String; public var itemHeight: String; public var itemPadding: String; public var labelName: String; public var valueName: String; public var customClick: Bool; public var wrap: Bool
    private var modelValue: Binding<String>?; private var onCustomClickHandler: ((String) -> Void)?
    public init(options: [UPChooseOption] = [], modelValue: Binding<String>? = nil, type: String = "radio", itemWidth: String = "auto", itemHeight: String = "50px", itemPadding: String = "8px", labelName: String = "title", valueName: String = "value", customClick: Bool = false, wrap: Bool = true) { self.options = options; self.modelValue = modelValue; self.type = type; self.itemWidth = itemWidth; self.itemHeight = itemHeight; self.itemPadding = itemPadding; self.labelName = labelName; self.valueName = valueName; self.customClick = customClick; self.wrap = wrap }
    public var body: some View { HStack { ForEach(options) { option in Button(option.title) { select(option.value) } } } }
    public func select(_ value: String) { if customClick { onCustomClickHandler?(value) } else { modelValue?.wrappedValue = value } }; public func onCustomClick(_ a: @escaping (String) -> Void) -> Self { var c = self; c.onCustomClickHandler = a; return c }
}
